/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddCustomerRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const CustomerId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'lastPurchaseDate' : IDL.Opt(Timestamp),
  'totalSpent' : IDL.Float64,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const AddEntryRequest = IDL.Record({
  'customerName' : IDL.Text,
  'itemDescription' : IDL.Text,
  'date' : Timestamp,
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : IDL.Float64,
});
export const EntryId = IDL.Nat;
export const RevenueEntry = IDL.Record({
  'id' : EntryId,
  'customerName' : IDL.Text,
  'itemDescription' : IDL.Text,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : IDL.Float64,
});
export const DailyComparison = IDL.Record({
  'today' : IDL.Float64,
  'yesterdayCount' : IDL.Nat,
  'yesterday' : IDL.Float64,
  'todayCount' : IDL.Nat,
});
export const PeriodMetrics = IDL.Record({
  'endDate' : Timestamp,
  'period' : IDL.Text,
  'totalRevenue' : IDL.Float64,
  'startDate' : Timestamp,
  'transactionCount' : IDL.Nat,
});
export const DailyRevenue = IDL.Record({
  'total' : IDL.Float64,
  'date' : Timestamp,
  'count' : IDL.Nat,
});
export const DateRangeFilter = IDL.Record({
  'to' : Timestamp,
  'from' : Timestamp,
});
export const RevenueSummary = IDL.Record({
  'dailyTotal' : IDL.Float64,
  'averageTransactionValue' : IDL.Float64,
  'totalRevenue' : IDL.Float64,
  'transactionCount' : IDL.Nat,
});
export const TopCustomer = IDL.Record({
  'customer' : Customer,
  'totalSpent' : IDL.Float64,
});
export const UpdateCustomerRequest = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateEntryRequest = IDL.Record({
  'id' : EntryId,
  'customerName' : IDL.Text,
  'itemDescription' : IDL.Text,
  'date' : Timestamp,
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([AddCustomerRequest], [Customer], []),
  'addRevenueEntry' : IDL.Func([AddEntryRequest], [RevenueEntry], []),
  'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'deleteRevenueEntry' : IDL.Func([EntryId], [IDL.Bool], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getCustomerTransactions' : IDL.Func(
      [CustomerId],
      [IDL.Vec(RevenueEntry)],
      ['query'],
    ),
  'getDailyComparison' : IDL.Func([], [DailyComparison], ['query']),
  'getMonthlyRevenue' : IDL.Func([], [IDL.Float64], ['query']),
  'getPeriodMetrics' : IDL.Func([IDL.Text], [PeriodMetrics], ['query']),
  'getRevenueByDay' : IDL.Func([IDL.Nat], [IDL.Vec(DailyRevenue)], ['query']),
  'getRevenueEntriesByCustomer' : IDL.Func(
      [CustomerId],
      [IDL.Vec(RevenueEntry)],
      ['query'],
    ),
  'getRevenueEntriesByDateRange' : IDL.Func(
      [DateRangeFilter],
      [IDL.Vec(RevenueEntry)],
      ['query'],
    ),
  'getRevenueSummary' : IDL.Func([], [RevenueSummary], ['query']),
  'getTopCustomers' : IDL.Func([IDL.Nat], [IDL.Vec(TopCustomer)], ['query']),
  'searchCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
  'updateCustomer' : IDL.Func([UpdateCustomerRequest], [IDL.Bool], []),
  'updateRevenueEntry' : IDL.Func([UpdateEntryRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddCustomerRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CustomerId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'lastPurchaseDate' : IDL.Opt(Timestamp),
    'totalSpent' : IDL.Float64,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AddEntryRequest = IDL.Record({
    'customerName' : IDL.Text,
    'itemDescription' : IDL.Text,
    'date' : Timestamp,
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : IDL.Float64,
  });
  const EntryId = IDL.Nat;
  const RevenueEntry = IDL.Record({
    'id' : EntryId,
    'customerName' : IDL.Text,
    'itemDescription' : IDL.Text,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : IDL.Float64,
  });
  const DailyComparison = IDL.Record({
    'today' : IDL.Float64,
    'yesterdayCount' : IDL.Nat,
    'yesterday' : IDL.Float64,
    'todayCount' : IDL.Nat,
  });
  const PeriodMetrics = IDL.Record({
    'endDate' : Timestamp,
    'period' : IDL.Text,
    'totalRevenue' : IDL.Float64,
    'startDate' : Timestamp,
    'transactionCount' : IDL.Nat,
  });
  const DailyRevenue = IDL.Record({
    'total' : IDL.Float64,
    'date' : Timestamp,
    'count' : IDL.Nat,
  });
  const DateRangeFilter = IDL.Record({ 'to' : Timestamp, 'from' : Timestamp });
  const RevenueSummary = IDL.Record({
    'dailyTotal' : IDL.Float64,
    'averageTransactionValue' : IDL.Float64,
    'totalRevenue' : IDL.Float64,
    'transactionCount' : IDL.Nat,
  });
  const TopCustomer = IDL.Record({
    'customer' : Customer,
    'totalSpent' : IDL.Float64,
  });
  const UpdateCustomerRequest = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateEntryRequest = IDL.Record({
    'id' : EntryId,
    'customerName' : IDL.Text,
    'itemDescription' : IDL.Text,
    'date' : Timestamp,
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([AddCustomerRequest], [Customer], []),
    'addRevenueEntry' : IDL.Func([AddEntryRequest], [RevenueEntry], []),
    'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'deleteRevenueEntry' : IDL.Func([EntryId], [IDL.Bool], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getCustomerTransactions' : IDL.Func(
        [CustomerId],
        [IDL.Vec(RevenueEntry)],
        ['query'],
      ),
    'getDailyComparison' : IDL.Func([], [DailyComparison], ['query']),
    'getMonthlyRevenue' : IDL.Func([], [IDL.Float64], ['query']),
    'getPeriodMetrics' : IDL.Func([IDL.Text], [PeriodMetrics], ['query']),
    'getRevenueByDay' : IDL.Func([IDL.Nat], [IDL.Vec(DailyRevenue)], ['query']),
    'getRevenueEntriesByCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Vec(RevenueEntry)],
        ['query'],
      ),
    'getRevenueEntriesByDateRange' : IDL.Func(
        [DateRangeFilter],
        [IDL.Vec(RevenueEntry)],
        ['query'],
      ),
    'getRevenueSummary' : IDL.Func([], [RevenueSummary], ['query']),
    'getTopCustomers' : IDL.Func([IDL.Nat], [IDL.Vec(TopCustomer)], ['query']),
    'searchCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
    'updateCustomer' : IDL.Func([UpdateCustomerRequest], [IDL.Bool], []),
    'updateRevenueEntry' : IDL.Func([UpdateEntryRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };