/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddCustomerRequest {
  'name' : string,
  'email' : string,
  'notes' : string,
  'phone' : string,
}
export interface AddEntryRequest {
  'customerName' : string,
  'itemDescription' : string,
  'date' : Timestamp,
  'notes' : string,
  'customerId' : CustomerId,
  'amount' : number,
}
export interface Customer {
  'id' : CustomerId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'lastPurchaseDate' : [] | [Timestamp],
  'totalSpent' : number,
  'notes' : string,
  'phone' : string,
}
export type CustomerId = bigint;
export interface DailyComparison {
  'today' : number,
  'yesterdayCount' : bigint,
  'yesterday' : number,
  'todayCount' : bigint,
}
export interface DailyRevenue {
  'total' : number,
  'date' : Timestamp,
  'count' : bigint,
}
export interface DateRangeFilter { 'to' : Timestamp, 'from' : Timestamp }
export type EntryId = bigint;
export interface PeriodMetrics {
  'endDate' : Timestamp,
  'period' : string,
  'totalRevenue' : number,
  'startDate' : Timestamp,
  'transactionCount' : bigint,
}
export interface RevenueEntry {
  'id' : EntryId,
  'customerName' : string,
  'itemDescription' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : string,
  'customerId' : CustomerId,
  'amount' : number,
}
export interface RevenueSummary {
  'dailyTotal' : number,
  'averageTransactionValue' : number,
  'totalRevenue' : number,
  'transactionCount' : bigint,
}
export type Timestamp = bigint;
export interface TopCustomer { 'customer' : Customer, 'totalSpent' : number }
export interface UpdateCustomerRequest {
  'id' : CustomerId,
  'name' : string,
  'email' : string,
  'notes' : string,
  'phone' : string,
}
export interface UpdateEntryRequest {
  'id' : EntryId,
  'customerName' : string,
  'itemDescription' : string,
  'date' : Timestamp,
  'notes' : string,
  'customerId' : CustomerId,
  'amount' : number,
}
export interface _SERVICE {
  'addCustomer' : ActorMethod<[AddCustomerRequest], Customer>,
  'addRevenueEntry' : ActorMethod<[AddEntryRequest], RevenueEntry>,
  'deleteCustomer' : ActorMethod<[CustomerId], boolean>,
  'deleteRevenueEntry' : ActorMethod<[EntryId], boolean>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllRevenueEntries' : ActorMethod<[], Array<RevenueEntry>>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [Customer]>,
  'getCustomerTransactions' : ActorMethod<[CustomerId], Array<RevenueEntry>>,
  'getDailyComparison' : ActorMethod<[], DailyComparison>,
  'getMonthlyRevenue' : ActorMethod<[], number>,
  'getPeriodMetrics' : ActorMethod<[string], PeriodMetrics>,
  'getRevenueByDay' : ActorMethod<[bigint], Array<DailyRevenue>>,
  'getRevenueEntriesByCustomer' : ActorMethod<
    [CustomerId],
    Array<RevenueEntry>
  >,
  'getRevenueEntriesByDateRange' : ActorMethod<
    [DateRangeFilter],
    Array<RevenueEntry>
  >,
  'getRevenueSummary' : ActorMethod<[], RevenueSummary>,
  'getTopCustomers' : ActorMethod<[bigint], Array<TopCustomer>>,
  'searchCustomers' : ActorMethod<[string], Array<Customer>>,
  'updateCustomer' : ActorMethod<[UpdateCustomerRequest], boolean>,
  'updateRevenueEntry' : ActorMethod<[UpdateEntryRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];