/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AddCustomerRequest {
    name: string;
    email: string;
    notes: string;
    phone: string;
}
export type Timestamp = bigint;
export interface UpdateCustomerRequest {
    id: CustomerId;
    name: string;
    email: string;
    notes: string;
    phone: string;
}
export interface RevenueEntry {
    id: EntryId;
    customerName: string;
    itemDescription: string;
    date: Timestamp;
    createdAt: Timestamp;
    notes: string;
    customerId: CustomerId;
    amount: number;
}
export interface Customer {
    id: CustomerId;
    name: string;
    createdAt: Timestamp;
    email: string;
    lastPurchaseDate?: Timestamp;
    totalSpent: number;
    notes: string;
    phone: string;
}
export interface RevenueSummary {
    dailyTotal: number;
    averageTransactionValue: number;
    totalRevenue: number;
    transactionCount: bigint;
}
export interface DailyRevenue {
    total: number;
    date: Timestamp;
    count: bigint;
}
export interface PeriodMetrics {
    endDate: Timestamp;
    period: string;
    totalRevenue: number;
    startDate: Timestamp;
    transactionCount: bigint;
}
export interface TopCustomer {
    customer: Customer;
    totalSpent: number;
}
export interface UpdateEntryRequest {
    id: EntryId;
    customerName: string;
    itemDescription: string;
    date: Timestamp;
    notes: string;
    customerId: CustomerId;
    amount: number;
}
export type EntryId = bigint;
export interface DateRangeFilter {
    to: Timestamp;
    from: Timestamp;
}
export type CustomerId = bigint;
export interface AddEntryRequest {
    customerName: string;
    itemDescription: string;
    date: Timestamp;
    notes: string;
    customerId: CustomerId;
    amount: number;
}
export interface DailyComparison {
    today: number;
    yesterdayCount: bigint;
    yesterday: number;
    todayCount: bigint;
}
export interface backendInterface {
    addCustomer(req: AddCustomerRequest): Promise<Customer>;
    addRevenueEntry(req: AddEntryRequest): Promise<RevenueEntry>;
    deleteCustomer(id: CustomerId): Promise<boolean>;
    deleteRevenueEntry(id: EntryId): Promise<boolean>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllRevenueEntries(): Promise<Array<RevenueEntry>>;
    getCustomer(id: CustomerId): Promise<Customer | null>;
    getCustomerTransactions(customerId: CustomerId): Promise<Array<RevenueEntry>>;
    getDailyComparison(): Promise<DailyComparison>;
    getMonthlyRevenue(): Promise<number>;
    getPeriodMetrics(period: string): Promise<PeriodMetrics>;
    getRevenueByDay(days: bigint): Promise<Array<DailyRevenue>>;
    getRevenueEntriesByCustomer(customerId: CustomerId): Promise<Array<RevenueEntry>>;
    getRevenueEntriesByDateRange(filter: DateRangeFilter): Promise<Array<RevenueEntry>>;
    getRevenueSummary(): Promise<RevenueSummary>;
    getTopCustomers(n: bigint): Promise<Array<TopCustomer>>;
    searchCustomers(nameQuery: string): Promise<Array<Customer>>;
    updateCustomer(req: UpdateCustomerRequest): Promise<boolean>;
    updateRevenueEntry(req: UpdateEntryRequest): Promise<boolean>;
}
import type { Customer as _Customer, CustomerId as _CustomerId, Timestamp as _Timestamp, TopCustomer as _TopCustomer } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: AddCustomerRequest): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return from_candid_Customer_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return from_candid_Customer_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRevenueEntry(arg0: AddEntryRequest): Promise<RevenueEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addRevenueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRevenueEntry(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: CustomerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteRevenueEntry(arg0: EntryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRevenueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRevenueEntry(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRevenueEntries(): Promise<Array<RevenueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRevenueEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRevenueEntries();
            return result;
        }
    }
    async getCustomer(arg0: CustomerId): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerTransactions(arg0: CustomerId): Promise<Array<RevenueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerTransactions(arg0);
            return result;
        }
    }
    async getDailyComparison(): Promise<DailyComparison> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyComparison();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyComparison();
            return result;
        }
    }
    async getMonthlyRevenue(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyRevenue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyRevenue();
            return result;
        }
    }
    async getPeriodMetrics(arg0: string): Promise<PeriodMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getPeriodMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPeriodMetrics(arg0);
            return result;
        }
    }
    async getRevenueByDay(arg0: bigint): Promise<Array<DailyRevenue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByDay(arg0);
            return result;
        }
    }
    async getRevenueEntriesByCustomer(arg0: CustomerId): Promise<Array<RevenueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueEntriesByCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueEntriesByCustomer(arg0);
            return result;
        }
    }
    async getRevenueEntriesByDateRange(arg0: DateRangeFilter): Promise<Array<RevenueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueEntriesByDateRange(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueEntriesByDateRange(arg0);
            return result;
        }
    }
    async getRevenueSummary(): Promise<RevenueSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueSummary();
            return result;
        }
    }
    async getTopCustomers(arg0: bigint): Promise<Array<TopCustomer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopCustomers(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopCustomers(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchCustomers(arg0: string): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCustomers(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCustomers(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: UpdateCustomerRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0);
            return result;
        }
    }
    async updateRevenueEntry(arg0: UpdateEntryRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRevenueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRevenueEntry(arg0);
            return result;
        }
    }
}
function from_candid_Customer_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_TopCustomer_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopCustomer): TopCustomer {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CustomerId;
    name: string;
    createdAt: _Timestamp;
    email: string;
    lastPurchaseDate: [] | [_Timestamp];
    totalSpent: number;
    notes: string;
    phone: string;
}): {
    id: CustomerId;
    name: string;
    createdAt: Timestamp;
    email: string;
    lastPurchaseDate?: Timestamp;
    totalSpent: number;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        lastPurchaseDate: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.lastPurchaseDate)),
        totalSpent: value.totalSpent,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: _Customer;
    totalSpent: number;
}): {
    customer: Customer;
    totalSpent: number;
} {
    return {
        customer: from_candid_Customer_n1(_uploadFile, _downloadFile, value.customer),
        totalSpent: value.totalSpent
    };
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TopCustomer>): Array<TopCustomer> {
    return value.map((x)=>from_candid_TopCustomer_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
